### ISSUE TITLE
Can Not Locate Block

### ISSUE THREAD

**Issue by TheJeffr0** [mkaz/juxtapose-block#10]
I wanted to try this block on WordPress 5.0.3 but after I install and activate the plugin, I can not locate the block in the Add Block menu. Is this a known issue?

**Comment by mkaz** [comment]
You should be able to see the block in the Layout category of the inserter.

![screenshot from 2019-01-28 09-54-49](https://user-images.githubusercontent.com/45363/51855729-cab00f80-22e2-11e9-9981-3b64228b7a65.png)

**Comment by mkaz** [comment]
This was due to an installation without the built JavaScript file. I've included the built file in the repo to avoid in the future.
